version: "3.8"

services:

  web1:
    image: rayyandevopss/web1-service:v1
    ports:
      - "5001:5001"
    networks:
      monitor-network:
        aliases:
          - web1-service

  web2:
    image: rayyandevopss/web2-service:v1
    ports:
      - "5002:5002"
    networks:
      monitor-network:
        aliases:
          - web2-service

  sarathi:
    image: rayyandevopss/sarathi-service:v1
    ports:
      - "5005:5001"
    networks:
      monitor-network:
        aliases:
          - sarathi

  executer:
    image: rayyandevopss/executer-service:v1
    ports:
      - "5003:5003"
    environment:
      - EXECUTION_MODE=simulate
      - SARATHI_URL=http://sarathi:5001/decision
      - PYTHONUNBUFFERED=1
    depends_on:
      - sarathi
    networks:
      monitor-network:
        aliases:
          - executer-service

  monitor:
    image: rayyandevopss/monitor-service:v4
    ports:
      - "5004:5004"
    environment:
      - EXECUTER_URL=http://executer-service:5003
      - POLL_INTERVAL=10
      - PYTHONUNBUFFERED=1
    depends_on:
      - web1
      - web2
      - executer
      - sarathi
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge