apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: rayyandevopss/detector-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: detector-service
spec:
  selector:
    app: detector
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP