apiVersion: v1
kind: ServiceAccount
metadata:
  name: executer-sa
  namespace: prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executer-role
  namespace: prod
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executer-binding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: executer-sa
  namespace: prod
roleRef:
  kind: Role
  name: executer-role
  apiGroup: rbac.authorization.k8s.io