apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarathi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sarathi
  template:
    metadata:
      labels:
        app: sarathi
    spec:
      containers:
      - name: sarathi
        image: rayyandevopss/sarathi-service:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sarathi
spec:
  selector:
    app: sarathi
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP