apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarathi
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sarathi
  template:
    metadata:
      labels:
        app: sarathi
    spec:
      containers:
      - name: sarathi
        image: rayyandevopss/sarathi-service:COMMIT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 5001

        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"

        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: sarathi-service
  namespace: prod
spec:
  selector:
    app: sarathi
  ports:
    - port: 5001
      targetPort: 5001