apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
      version: green
  template:
    metadata:
      labels:
        app: web1
        version: green
    spec:
      containers:
      - name: web1
        image: rayyandevopss/web1-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5001

        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10