apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
      env: staging
  template:
    metadata:
      labels:
        app: monitor
        env: staging
    spec:
      containers:
      - name: monitor
        image: rayyandevopss/monitor-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5004

        env:
        - name: SARATHI_URL
          value: "http://sarathi-staging-service:5001"

        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: monitor-staging-service
spec:
  selector:
    app: monitor
    env: staging
  ports:
    - port: 5004
      targetPort: 5004